- name: setup spring boot
  hosts: app_server
  vars:
    springboot_application_name: "{{ lookup('env','APP_NAME') }}"
    springboot_src_url: "{{ lookup('env','ARTIFACT_URL') }}"
    springboot_deploy_folder: /home/ec2-user
    springboot_user: root
    springboot_group: root
  roles:
    - role: ansible-springboot-role
