---
- name: "Check if use systemd"
  set_fact: |
    use_system_d={{ (ansible_distribution == 'Debian')
    or (ansible_distribution in ['RedHat','CentOS','Amazon','Ubuntu'])}}

- name: "Ensure systemd system directory is present (for Ubuntu)"
  file:
    path: "{{ sysd_user_services_folder }}"
    state: directory
    owner: root
    group: root

- name: "Create systemd service file"
  template:
    src: app.service.j2
    dest: "{{ sysd_script }}"
    mode: +x 
    owner: "{{ springboot_user }}"
    group: "{{ springboot_group }}"
  when: use_system_d
  notify:
    - "Restart application"
